##七牛云的key
##qiniu:
##  accessKey: canKgBzqR_AN_EviuOuWYUT4Vko3gi5dTNZFiQ4C
 ## secretKey: feAWGHn_UmhGU2ckkHd9F2q2qFpC7lPqlemvEOCH
 ## bucketName: eumji025
 ## basePath: http://of8rkrh1w.bkt.clouddn.com/

## 百度推送
##baidu:
##  task:
 ##   postUrl: http://data.zz.baidu.com/urls?site=www.eumji025.com&token=hHzO6TjfJBf4KA53
 ##   baseUrl: http://www.eumji025.com

#数据库连接配置
spring:
  thymeleaf:
    mode: HTML5
  #字符集和json格式工具
  http:
    encoding:
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
    multipart:
      max-file-size: 10MB
  application:
    name: lifeweb
  ## Redis 配置
  redis:
  ## Redis数据库索引（默认为0）
  database : 0
  ## Redis服务器地址
  host : 127.0.0.1
  ## Redis服务器连接端口
  port : 6379
  ## Redis服务器连接密码（默认为空）
  password : 
  ## 连接池最大连接数（使用负值表示没有限制）
  ## 连接超时时间（毫秒）
  timeout : 0
  pool:
      max-active : 8
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait : -1
      ## 连接池中的最大空闲连接
      max-idle : 8
      ## 连接池中的最小空闲连接
      min-idle : 0

#关闭服务
endpoints:
  shutdown:
      enabled : true
      sensitive : false

#mynatis配置
##mybatis:
##  type-aliases-package: com.eumji.zblog.vo
  #mapper加载路径
##  mapper-locations: classpath:mapper/*Mapper.xml
  #myatbis配置文件
 ## config-location: classpath:mybatis-conf.xml
#加载log4j2
logging:
  config: classpath:log4j2.xml
  level: debug
  file: web.log
server:
  session-timeout : 3600
  port: 8089
